name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  create-env-files:


  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: Install dependencies
        run: yarn
      - run: yarn run build
      - run: yarn run test
