name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Env vars
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}
        run: echo $TEST_ENV | base64 --decode > .env
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
          cache: 'npm'
      - name: Install dependencies
        run: yarn
      - name: Tests
        run: yarn test
