name: Run Tests DEV

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    environment: DEV #reference to the GitHub Repository Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Env vars
        env: #reference to the job environment
          ENV_TEST: ${{ secrets.ENV_TEST }}
        run: |
          echo $ENV_TEST | base64 --decode > .env
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
          cache: 'npm'
      - name: Install dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test
